// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp1_nmmXC_O8k2N7fSny5FvHLFGm1nEco',
    appId: '1:715572141771:web:7a2c223e8dc05916dbc54e',
    messagingSenderId: '715572141771',
    projectId: 'fir-app-89570',
    authDomain: 'fir-app-89570.firebaseapp.com',
    storageBucket: 'fir-app-89570.firebasestorage.app',
    measurementId: 'G-MH5RFEZ8JX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6qxNAY1t_pfrcPET_7_2effgyYszOezA',
    appId: '1:715572141771:android:dbe942fb3bb4f93edbc54e',
    messagingSenderId: '715572141771',
    projectId: 'fir-app-89570',
    storageBucket: 'fir-app-89570.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChsdJt6dMKTSCQViHgRE9ZOOqqIfUUNjI',
    appId: '1:715572141771:ios:89f121e653aa96c7dbc54e',
    messagingSenderId: '715572141771',
    projectId: 'fir-app-89570',
    storageBucket: 'fir-app-89570.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChsdJt6dMKTSCQViHgRE9ZOOqqIfUUNjI',
    appId: '1:715572141771:ios:89f121e653aa96c7dbc54e',
    messagingSenderId: '715572141771',
    projectId: 'fir-app-89570',
    storageBucket: 'fir-app-89570.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCp1_nmmXC_O8k2N7fSny5FvHLFGm1nEco',
    appId: '1:715572141771:web:cb71a539c7d0cafddbc54e',
    messagingSenderId: '715572141771',
    projectId: 'fir-app-89570',
    authDomain: 'fir-app-89570.firebaseapp.com',
    storageBucket: 'fir-app-89570.firebasestorage.app',
    measurementId: 'G-S5NCCBSE91',
  );
}
